//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Docker
{
    using System;
    using System.Collections.Generic;
    
    public partial class EditSet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EditSet()
        {
            this.Money = 0F;
        }
    
        public string Username { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public float Money { get; set; }
        public int CanUseNum { get; set; }
        public int Identity { get; set; }
        public int User_Id { get; set; }
    }
}
